version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
jobs:

  build:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker build -t circleci-docker-in-docker:0.1 --target build .

  publish:
    machine: true
    steps:
      - checkout
      - run: docker build -t circleci-docker-in-docker:0.1 --target production .
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: circleci-docker-in-docker
          tag: "0.1"
  
  deploy:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker image ls


workflows:
  build-and-approval-deploy:
    jobs:
      - build
      - publish
      - hold-deploy:
          type: approval
          requires:
            - publish
      - deploy:
          requires:
            - hold-deploy
