version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker build -t circleci-docker-in-docker:0.1 --target build .

  deploy:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker image ls


workflows:
  version: 2
  build-and-approval-deploy:
    jobs:
      - build
      - hold-deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold-deploy
