version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
jobs:

  build:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - gcp-gcr/build-image:
          image: circleci-docker-in-docker
          tag: "0.1"
          extra_build_args: "--target build"

  publish:
    machine: true
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: circleci-docker-in-docker
          extra_build_args: "--target production"
          tag: "0.1"
      - gcp-gcr/push-image:
          image: circleci-docker-in-docker
          tag: "0.1"
  
  deploy:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker image ls


workflows:
  build-and-approval-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
      - hold-deploy:
          type: approval
          requires:
            - publish
      - deploy:
          requires:
            - hold-deploy
