version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0
  gcp-gke: circleci/gcp-gke@1.1.0
jobs:

  build:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: env
      - run: echo $SECRET_VAR > .env
      - run: DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t circleci-docker-in-docker:0.1 --target build --secret id=env,src=.env .
      #- gcp-gcr/build-image:
      #    image: circleci-docker-in-docker
      #    extra_build_args: "--target build"
      #    tag: "0.1"

  publish:
    machine: true
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: circleci-docker-in-docker
          extra_build_args: "--target production"
          tag: "0.1"
      - gcp-gcr/push-image:
          image: circleci-docker-in-docker
          tag: "0.1"
  
  deploy:
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: cluster-1
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: cluster-1
          deployment: circleci-docker-in-docker
          container: circleci-dind
          image: gcr.io/virtual-crane-285416/circleci-docker-in-docker
          tag: "0.1"


workflows:
  build-and-approval-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
      - hold-deploy:
          type: approval
          requires:
            - publish
      - deploy:
          requires:
            - hold-deploy
