version: 2
jobs:
  build:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker build -t circleci-docker-in-docker:0.1 --target build .

  deploy:
    docker: 
      - image: docker:dind
    steps:
      - run: pwd
      - run: ls -l
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -l
      - run: cksum src/server.py 
      - run: docker image ls


workflows:
  version: 2
  build-and-approval-deploy:
    jobs:
      - build
      - hold-deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold-deploy
