apiVersion: v1
kind: Service
metadata:
  name: circleci-docker-in-docker-service
  labels:
    app: docker-in-docker-service
spec:
  ports:
    - port: 80
  selector:
    tier: frontend
  type: LoadBalancer
